
name: Waka Readme

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 12am IST
    - cron: '10 2 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WT_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_COMMIT: "false"
          SHOW_LOC_CHART: "false"
          SHOW_EDITORS: "false"
          SHOW_TIMEZONE: "false"
          SHOW_PROJECTS: "false"
          SHOW_OS: "false"
